### ISSUE TITLE
Processo Endogenia

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#127]
Uma das coisas que comentamos ano passado era verificar a possibilidade de gerar o relatório de endogenia na própria plataforma. Hoje, acontece da seguinte maneira:

1) Editores preenchem formulário Excel com os seguintes dados (Corpo Editorial, Autores, Revisores Ad-Hoc):
Volume
Número
Ano
Página Inicial
Título do Artigo
Nome
Instituição
Unidade
Departamento
Cidade
Estado
País
Link para CV Lattes

2) Informações são juntadas num mesmo arquivo e normalizadas

3) Endogenia é gerada (.dos?)

4) Resultados, por revista:
Título do periódico
Fascículos analisados
Total de autores
Total de artigos
Média de autores por artigo
Máximo de autores por artigo
Artigos com autores únicos Brasileiros
Artigos com participação de autores nacionais de mesma instituição
Artigos com participação de autores nacionais de instituições distintas
Artigos com colaboração de autor estrangeiro associado a autor nacional
Artigos com autores estrangeiros
Total de Instituições
Total de Estados
Total de Países
Predominância do Estado (UF / %)
Autores dos artigos / Comitê editorial / Conselho de revisores
Por instituição (individual e total)
Por estado (individual e total)
Por país (individual e total)

→ Proposta:

• Informações serem preenchidas na própria plataforma de avaliação
• Opções controladas de preenchimento de Cidade, Estado, País e Instituição (para já ser normalizado)
• Geração automática de relatório de endogenia

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula Algumas dúvidas:

Artigos com participação de autores nacionais de mesma instituição **(todos os autores devem ser da mesma instituição?)**

Artigos com participação de autores nacionais de instituições distintas **(todos os autores devem ser de diferentes instituições?)**

Artigos com colaboração de autor estrangeiro associado a autor nacional **(o que determina a associação entre o autor estrangeiro e o autor nacional)**

Artigos com autores estrangeiros **(todos os autores ou pelo menos 1 estrangeiro)**

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula sobre os itens abaixo:

Autores dos artigos / Comitê editorial / Conselho de revisores
Por instituição (individual e total)
Por estado (individual e total)
Por país (individual e total)

Se espera ter o número total de autores / editores / revisores por instituição, estado e país?
O que se espera quando se fala em individual e total?

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura estou tentando entrar nas revistas que foram avaliadas no ano passado para pegar um exemplo de relatório de endogenia, mas aparece o seguinte erro:

![image](https://user-images.githubusercontent.com/47643830/85586479-57b1e200-b617-11ea-8841-bbedab8593cf.png)

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki 

Observando relatórios dos anos anteriores, acredito que seja assim:

• Artigos com participação de autores nacionais de mesma instituição (todos os autores devem ser da mesma instituição)
• Artigos com participação de autores nacionais de instituições distintas (pelo menos um autor de instituição diferente ou no mínimo, duas instituições diferentes)
• Artigos com colaboração de autor estrangeiro associado a autor nacional (pelo menos 1 autor do Brasil e 1 de fora)
• Artigos com autores estrangeiros (somente autores estrangeiros) ← acredito que seria melhor "Artigos de autores estrangeiros"

• Se espera ter o número total de autores / editores / revisores por instituição, estado e país? Sim!
• Individual - número de autores/editores/revisores por instituição, estado e país
• Total - número total de autores/editores/revisores

@suelisuga Se possível, validar!

Exemplo:

Título do periódico: Revista Contexto & Saude
Fascículos analisados: '2017 16(32); 2017 17(33); 2018 18(34)'

Total de autores: 192
Total de artigos: 50
Média de autores por artigo: 4.02
Máximo de autores por artigo: 8
Artigos com autores únicos Brasileiros: 2
Artigos com participação de autores nacionais de mesma instituição: 28
Artigos com participação de autores nacionais de instituições distintas: 18
Artigos com colaboração de autor estrangeiro associado a autor nacional: 1
Artigos com autores estrangeiros: 1
Total de Instituições: 46
Total de Estados: 15
Total de Países: 3
Predominância do Estado: RS 57.71%

AUTORES DOS ARTIGOS
--
 
POR INSTITUIÇÃO
UNIVERSIDADE FEDERAL DE PELOTAS - PELOTAS | 21 | 10.45%
UNIVERSIDADE DE PASSO FUNDO - PASSO FUNDO | 16 | 7.96%
UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL - PORTO ALEGRE | 15 | 7.46%
UNIVERSIDADE FEDERAL DO PAMPA - BAGE | 12 | 5.97%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - IJUI | 12 | 5.97%
CENTRO UNIVERSITARIO DA SERRA GAUCHA - CAXIAS DO SUL | 11 | 5.47%
UNIVERSIDADE FEDERAL DO PIAUI - TERESINA | 7 | 3.48%
CENTRO UNIVERSITARIO NOSSA SENHORA DO PATROCINIO - ITU | 6 | 2.99%
NOVA FACULDADE - CONTAGEM | 6 | 2.99%
UNIVERSIDADE FEDERAL DE SANTA MARIA - SANTA MARIA | 6 | 2.99%
INSTITUTO SUPERIOR DE TEOLOGIA APLICADA - SOBRAL | 5 | 2.49%
UNIVERSIDADE DO VALE DO TAQUARI - LAJEADO | 5 | 2.49%
FACULDADES UNIDAS DO NORTE DE MINAS - MONTES CLAROS | 4 | 1.99%
UNIVERSIDADE DA AMAZONIA - BELEM | 4 | 1.99%
UNIVERSIDADE DE TAUBATE - TAUBATE | 4 | 1.99%
UNIVERSIDADE ESTADUAL DE MONTES CLAROS - MONTES CLAROS | 4 | 1.99%
UNIVERSIDADE FEDERAL DE JUIZ DE FORA - JUIZ DE FORA | 4 | 1.99%
UNIVERSIDADE FEDERAL DE PERNAMBUCO - RECIFE | 4 | 1.99%
UNIVERSIDADE FEDERAL DO PARANA - CURITIBA | 4 | 1.99%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - NAO INFORMADO | 4 | 1.99%
FUNDACAO ESCOLA DE SAUDE PUBLICA DE PALMAS - PALMAS | 3 | 1.49%
INSTITUTO CENECISTA DE ENSINO SUPERIOR DE SANTO ANGELO - SANTO ANGELO | 3 | 1.49%
INSTITUTO UNIVERSITARIO DE CIENCIAS DE LA SALUD FUND. HECTOR A. BARCELO - SAN TOME | 3 | 1.49%
UNIVERSIDADE ESTADUAL DE CAMPINAS - CAMPINAS | 3 | 1.49%
UNIVERSIDADE PARANAENSE - TOLEDO | 3 | 1.49%
UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUAI E DAS MISSOES - SANTO ANGELO | 3 | 1.49%
CENTRO UNIVERSITARIO FRANCISCANO - SANTA MARIA | 2 | 1.00%
FACULDADE SAO PAULO - ROLIM DE MOURA | 2 | 1.00%
REDE BRASILEIRA DE ENFERMAGEM E SEGURANCA DO PACIENTE - UBERLANDIA | 2 | 1.00%
UNIVERSIDADE FEDERAL DA PARAIBA - JOAO PESSOA | 2 | 1.00%
UNIVERSIDADE FEDERAL DE MINAS GERAIS - BELO HORIZONTE | 2 | 1.00%
UNIVERSIDADE FEDERAL DO PARA - BELEM | 2 | 1.00%
UNIVERSIDADE FEDERAL DO RIO GRANDE - RIO GRANDE | 2 | 1.00%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - PORTO ALEGRE | 2 | 1.00%
ARIZONA STATE UNIVERSITY - TEMPE | 1 | 0.50%
INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA DO CEARA - SOBRAL | 1 | 0.50%
UNIDADE BASICA DE SAUDE DE BOA VISTA DO SUL - BOA VISTA DO SUL | 1 | 0.50%
UNIDADE BASICA DE SAUDE DE PORTO ALEGRE - PORTO ALEGRE | 1 | 0.50%
UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE - BELEM | 1 | 0.50%
UNIVERSIDADE DO OESTE DO PARANA - CASCAVEL | 1 | 0.50%
UNIVERSIDADE DO VALE DO SAPUCAI - POUSO ALEGRE | 1 | 0.50%
UNIVERSIDADE ESTADUAL DO NORTE PIONEIRO - JACAREZINHO | 1 | 0.50%
UNIVERSIDADE ESTADUAL VALE DO ACARAU - SOBRAL | 1 | 0.50%
UNIVERSIDADE FEDERAL DE ALAGOAS - MACEIO | 1 | 0.50%
UNIVERSIDADE FEDERAL DE RONDONIA - PORTO VELHO | 1 | 0.50%
UNIVERSIDADE FEDERAL DE SANTA CATARINA - FLORIANOPOLIS | 1 | 0.50%
UNIVERSIDADE FEDERAL DE SAO PAULO - SAO PAULO | 1 | 0.50%
TOTAL | 201 | 100.00%
 
POR ESTADO
RS | 116 | 57.71%
MG | 23 | 11.44%
SP | 14 | 6.97%
PR | 8 | 3.98%
CE | 7 | 3.48%
PA | 7 | 3.48%
PI | 7 | 3.48%
PE | 4 | 1.99%
CORRIENTES | 3 | 1.49%
RO | 3 | 1.49%
TO | 3 | 1.49%
PB | 2 | 1.00%
SC | 2 | 1.00%
AL | 1 | 0.50%
ARIZONA | 1 | 0.50%
TOTAL | 201 | 100.00%
 
POR PAIS
BRASIL | 201 | 100.00%
TOTAL | 201 | 100.00%
 
COMITÊ EDITORIAL
 
POR INSTITUIÇÃO
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - IJUI	8	57.14%
INSTITUTO DE CARDIOLOGIA DE CRUZ ALTA - CRUZ ALTA	1	7.14%
UNIVERSIDADE DO EXTREMO SUL CATARINENSE - CRICIUMA	1	7.14%
UNIVERSIDADE FEDERAL DA FRONTEIRA SUL - CHAPECO	1	7.14%
UNIVERSIDADE FEDERAL DE SANTA MARIA - PALMEIRA DAS MISSOES	1	7.14%
UNIVERSIDADE FEDERAL DO PAMPA - ITAQUI	1	7.14%
UNIVERSIDADE FEDERAL DO PARANA - CURITIBA	1	7.14%
TOTAL	14	100.00%
 
POR ESTADO
RS	11	78.57%
SC	2	14.29%
PR	1	7.14%
TOTAL	14	100.00%
 
POR PAIS
BRASIL	14	100.00%
TOTAL	14	100.00%

**Comment by suelisuga** [comment]
@renatomurasaki e @AngelicaSAPaula é isso mesmo.
Mandei o mesmo exemplo em pdf por e-mail.

Abraços,
Sueli

**Comment by suelisuga** [comment]
@renatomurasaki e @de Paula, Srta. Angelica (BIR)<mailto:depaulang@paho.org>
Segue relatório feito em anos anteriores.

Abraços,

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:cd1bc0fa-0277-4d74-bac7-2c9436d6eddf]
________________________________
De: AngelicaSAPaula <notifications@github.com>
Enviado: quarta-feira, 24 de junho de 2020 12:49
Para: bireme/lilacs-journal-selection <lilacs-journal-selection@noreply.github.com>
Cc: Suga, Sueli Mitiko Yano (BIR) <sugasuel@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/lilacs-journal-selection] Processo Endogenia (#127)


@renatomurasaki<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenatomurasaki&data=02%7C01%7Csugasuel%40paho.org%7Caf9d6d80564a482e635308d818563efe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637286105989377491&sdata=kCuIj7i6uVWjABa1WLcuSjY1ZVJ4f02fasQSCGGz%2FDM%3D&reserved=0>

Observando relatórios dos anos anteriores, acredito que seja assim:

• Artigos com participação de autores nacionais de mesma instituição (todos os autores devem ser da mesma instituição)
• Artigos com participação de autores nacionais de instituições distintas (pelo menos um autor de instituição diferente ou no mínimo, duas instituições diferentes)
• Artigos com colaboração de autor estrangeiro associado a autor nacional (pelo menos 1 autor do Brasil e 1 de fora)
• Artigos com autores estrangeiros (somente autores estrangeiros) ← acredito que seria melhor "Artigos de autores estrangeiros"

• Se espera ter o número total de autores / editores / revisores por instituição, estado e país? Sim!
• Individual - número de autores/editores/revisores por instituição, estado e país
• Total - número total de autores/editores/revisores

@suelisuga<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuelisuga&data=02%7C01%7Csugasuel%40paho.org%7Caf9d6d80564a482e635308d818563efe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637286105989377491&sdata=XOoz0y2KIGd5PBTg7c11%2FVNPHG6UdtoftLKXL6TcxSg%3D&reserved=0> Se possível, validar!

Exemplo:

Título do periódico: Revista Contexto & Saude
Fascículos analisados: '2017 16(32); 2017 17(33); 2018 18(34)'

Total de autores: 192
Total de artigos: 50
Média de autores por artigo: 4.02
Máximo de autores por artigo: 8
Artigos com autores únicos Brasileiros: 2
Artigos com participação de autores nacionais de mesma instituição: 28
Artigos com participação de autores nacionais de instituições distintas: 18
Artigos com colaboração de autor estrangeiro associado a autor nacional: 1
Artigos com autores estrangeiros: 1
Total de Instituições: 46
Total de Estados: 15
Total de Países: 3
Predominância do Estado: RS 57.71%

AUTORES DOS ARTIGOS


POR INSTITUIÇÃO
UNIVERSIDADE FEDERAL DE PELOTAS - PELOTAS | 21 | 10.45%
UNIVERSIDADE DE PASSO FUNDO - PASSO FUNDO | 16 | 7.96%
UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL - PORTO ALEGRE | 15 | 7.46%
UNIVERSIDADE FEDERAL DO PAMPA - BAGE | 12 | 5.97%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - IJUI | 12 | 5.97%
CENTRO UNIVERSITARIO DA SERRA GAUCHA - CAXIAS DO SUL | 11 | 5.47%
UNIVERSIDADE FEDERAL DO PIAUI - TERESINA | 7 | 3.48%
CENTRO UNIVERSITARIO NOSSA SENHORA DO PATROCINIO - ITU | 6 | 2.99%
NOVA FACULDADE - CONTAGEM | 6 | 2.99%
UNIVERSIDADE FEDERAL DE SANTA MARIA - SANTA MARIA | 6 | 2.99%
INSTITUTO SUPERIOR DE TEOLOGIA APLICADA - SOBRAL | 5 | 2.49%
UNIVERSIDADE DO VALE DO TAQUARI - LAJEADO | 5 | 2.49%
FACULDADES UNIDAS DO NORTE DE MINAS - MONTES CLAROS | 4 | 1.99%
UNIVERSIDADE DA AMAZONIA - BELEM | 4 | 1.99%
UNIVERSIDADE DE TAUBATE - TAUBATE | 4 | 1.99%
UNIVERSIDADE ESTADUAL DE MONTES CLAROS - MONTES CLAROS | 4 | 1.99%
UNIVERSIDADE FEDERAL DE JUIZ DE FORA - JUIZ DE FORA | 4 | 1.99%
UNIVERSIDADE FEDERAL DE PERNAMBUCO - RECIFE | 4 | 1.99%
UNIVERSIDADE FEDERAL DO PARANA - CURITIBA | 4 | 1.99%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - NAO INFORMADO | 4 | 1.99%
FUNDACAO ESCOLA DE SAUDE PUBLICA DE PALMAS - PALMAS | 3 | 1.49%
INSTITUTO CENECISTA DE ENSINO SUPERIOR DE SANTO ANGELO - SANTO ANGELO | 3 | 1.49%
INSTITUTO UNIVERSITARIO DE CIENCIAS DE LA SALUD FUND. HECTOR A. BARCELO - SAN TOME | 3 | 1.49%
UNIVERSIDADE ESTADUAL DE CAMPINAS - CAMPINAS | 3 | 1.49%
UNIVERSIDADE PARANAENSE - TOLEDO | 3 | 1.49%
UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUAI E DAS MISSOES - SANTO ANGELO | 3 | 1.49%
CENTRO UNIVERSITARIO FRANCISCANO - SANTA MARIA | 2 | 1.00%
FACULDADE SAO PAULO - ROLIM DE MOURA | 2 | 1.00%
REDE BRASILEIRA DE ENFERMAGEM E SEGURANCA DO PACIENTE - UBERLANDIA | 2 | 1.00%
UNIVERSIDADE FEDERAL DA PARAIBA - JOAO PESSOA | 2 | 1.00%
UNIVERSIDADE FEDERAL DE MINAS GERAIS - BELO HORIZONTE | 2 | 1.00%
UNIVERSIDADE FEDERAL DO PARA - BELEM | 2 | 1.00%
UNIVERSIDADE FEDERAL DO RIO GRANDE - RIO GRANDE | 2 | 1.00%
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - PORTO ALEGRE | 2 | 1.00%
ARIZONA STATE UNIVERSITY - TEMPE | 1 | 0.50%
INSTITUTO FEDERAL DE EDUCACAO, CIENCIA E TECNOLOGIA DO CEARA - SOBRAL | 1 | 0.50%
UNIDADE BASICA DE SAUDE DE BOA VISTA DO SUL - BOA VISTA DO SUL | 1 | 0.50%
UNIDADE BASICA DE SAUDE DE PORTO ALEGRE - PORTO ALEGRE | 1 | 0.50%
UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE - BELEM | 1 | 0.50%
UNIVERSIDADE DO OESTE DO PARANA - CASCAVEL | 1 | 0.50%
UNIVERSIDADE DO VALE DO SAPUCAI - POUSO ALEGRE | 1 | 0.50%
UNIVERSIDADE ESTADUAL DO NORTE PIONEIRO - JACAREZINHO | 1 | 0.50%
UNIVERSIDADE ESTADUAL VALE DO ACARAU - SOBRAL | 1 | 0.50%
UNIVERSIDADE FEDERAL DE ALAGOAS - MACEIO | 1 | 0.50%
UNIVERSIDADE FEDERAL DE RONDONIA - PORTO VELHO | 1 | 0.50%
UNIVERSIDADE FEDERAL DE SANTA CATARINA - FLORIANOPOLIS | 1 | 0.50%
UNIVERSIDADE FEDERAL DE SAO PAULO - SAO PAULO | 1 | 0.50%
TOTAL | 201 | 100.00%

POR ESTADO
RS | 116 | 57.71%
MG | 23 | 11.44%
SP | 14 | 6.97%
PR | 8 | 3.98%
CE | 7 | 3.48%
PA | 7 | 3.48%
PI | 7 | 3.48%
PE | 4 | 1.99%
CORRIENTES | 3 | 1.49%
RO | 3 | 1.49%
TO | 3 | 1.49%
PB | 2 | 1.00%
SC | 2 | 1.00%
AL | 1 | 0.50%
ARIZONA | 1 | 0.50%
TOTAL | 201 | 100.00%

POR PAIS
BRASIL | 201 | 100.00%
TOTAL | 201 | 100.00%

COMITÊ EDITORIAL

POR INSTITUIÇÃO
UNIVERSIDADE REGIONAL DO NOROESTE DO ESTADO DO RIO GRANDE DO SUL - IJUI 8 57.14%
INSTITUTO DE CARDIOLOGIA DE CRUZ ALTA - CRUZ ALTA 1 7.14%
UNIVERSIDADE DO EXTREMO SUL CATARINENSE - CRICIUMA 1 7.14%
UNIVERSIDADE FEDERAL DA FRONTEIRA SUL - CHAPECO 1 7.14%
UNIVERSIDADE FEDERAL DE SANTA MARIA - PALMEIRA DAS MISSOES 1 7.14%
UNIVERSIDADE FEDERAL DO PAMPA - ITAQUI 1 7.14%
UNIVERSIDADE FEDERAL DO PARANA - CURITIBA 1 7.14%
TOTAL 14 100.00%

POR ESTADO
RS 11 78.57%
SC 2 14.29%
PR 1 7.14%
TOTAL 14 100.00%

POR PAIS
BRASIL 14 100.00%
TOTAL 14 100.00%

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Flilacs-journal-selection%2Fissues%2F127%23issuecomment-648904364&data=02%7C01%7Csugasuel%40paho.org%7Caf9d6d80564a482e635308d818563efe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637286105989387486&sdata=a7qVG35%2FbNh8t6TKHom2QRmCtO4bTIOrM9Qz80rllTQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UE3K3557BQNH3SZN7B3RYIOCJANCNFSM4KTAFSEQ&data=02%7C01%7Csugasuel%40paho.org%7Caf9d6d80564a482e635308d818563efe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637286105989387486&sdata=uzRhWUFf1Cwk4niwdIw9Mm94l1hY55yxmWZeN5AjZIw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula favor verificar se o acesso aos dados das revistas foi normalizado.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura agora está certinho! obrigada!

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula temos uma versão preliminar da endogenia utilizando o Tableau Desktop e a planilha Excel disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/endogenia-lilacs/dashboard

Por favor, poderia verificar se os números presentes nesta visualização coincidem com o relatório do ano passado?

Caso haja alguma dúvida ou discrepância nos números, atualize o issue, por favor.

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki boa tarde! Fiz uma análise comparativa das informações e segue em anexo. 

[Tableau_Endogenia.xlsx](https://github.com/bireme/lilacs-journal-selection/files/4854213/Tableau_Endogenia.xlsx)

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula segue a planilha comparativa atualizada [Tableau_Endogenia.xlsx](https://github.com/bireme/lilacs-journal-selection/files/4859699/Tableau_Endogenia.xlsx) pois faltaram os dados das colunas K, L, M e N que correspondem as linhas destacadas na imagem abaixo

![image](https://user-images.githubusercontent.com/1226218/86278000-0b821700-bbae-11ea-959d-c52824a71292.png)

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula vou checar a origem das diferenças.

Sobre a média de autores por artigo, não consegui entender a diferença de cálculo. Por exemplo, para o periódico "Arquivos de Asma, Alergia e Imunologia" temos os mesmos totais de autores e artigos, tanto no processo legado de endogenia, como no novo via Tableau. Estou fazendo o cálculo simples de Total de Autores / Total de Artigos, ou seja 141/48 = 2,94. Achei estranho o processo legado calcular 4,31. Você tem alguma hipótese sobre essa diferença?

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki pelo que verifiquei, o cálculo realizado no processo anterior considerava a quantidade total de autores, mesmo os repetidos. No processo atual, no Tableau, as repetições são desconsideradas (o que acredito ser o correto).

Verifiquei a planilha novamente, com as informações acrescidas!

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula eu estava com esta suspeita. Infelizmente a endogenia anterior tinha esta deficiência. Vou verificar os demais números para ver se encontro inconsistência nos cálculos do Tableau.

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki Boa tarde!

Em conversa com a equipe FIR, temos algumas sugestões de adaptação da visualização e gostaríamos de verificar se é possível realizá-las.

**1)** Ao escolher uma revista, o filtro "Fascículo" continua mostrando o de todas as revistas. Poderia ser verificado, para mostrar somente os fascículos correspondentes à revista selecionada?

![image](https://user-images.githubusercontent.com/47643830/88831967-753e1280-d1a6-11ea-94d7-1e4c42e22965.png)

**2)** Tirar caixa alta e negrito e dar mais ênfase ao resultado, além de colocar estas informações em linhas, uma abaixo da outra.

![image](https://user-images.githubusercontent.com/47643830/88832002-838c2e80-d1a6-11ea-8ca2-59bb431707d2.png)

**3)** No primeiro dashboard (Planilha Autores), acreditamos não ser necessária a visualização por artigo, mas somente dos totais (como era no processo anterior).

![image](https://user-images.githubusercontent.com/47643830/88832070-a28ac080-d1a6-11ea-886a-1456a45be399.png)

► **Dúvida:** Como sugerem a disponibilização deste conteúdo aos membros do Comitê? Enviamos o link ou geramos um documento em PDF? (no sistema, é obrigatória a inclusão de um documento referente ao processo de Endogenia para continuar para a segunda fase de avaliação)

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula republiquei a visualização dos indicadores de endogenia e comento que:

- O filtro de fásciculo está contextualizado com o filtro de revista e vice-versa
- Mudanças realizadas conforme solicitado nos itens 2 e 3. É preciso saber que alguns indicadores são de dificil cálculo e por isso a lista de artigos acaba sendo mostrada, pois são combinações de filtros e regras de conjunto para se chegar no resultado desejado. O que foi feito foi destacar a linha de total, mas se clicar na barra de scroll down será possível ver a lista de documentos.
- Ainda não foi possível calcular corretamente o número de "Artigos com autores únicos brasileiros" e "Artigos com autores únicos estrangeiros", pois as operações de conjunto com a estrutura de dados da planilha atual estão complexas. Entretanto encontrei um workaround gráfico que pode dar esse números, interpretando histogramas, como se vê abaixo:

![image](https://user-images.githubusercontent.com/1226218/88932790-eb994e00-d254-11ea-8f5e-0e2e4ad6642d.png)

O histograma acima mostra o seguinte: as barras dentro da área vermelha são os artigos que tem autores com mais de um país de afiliação. É possível ver que 2 documentos tem autores brasileiros com co-autoria de franceses e 1 documento de brasileiros com alemão. Os demais artigos que estão na área verde são somente com autores brasileiros.

Agora veja este próximo histograma:

![image](https://user-images.githubusercontent.com/1226218/88933424-c48f4c00-d255-11ea-803c-b49ea6ef407a.png)

Os artigos dentro da área vermelha mostram 1 artigo de co-autoria de brasileiros e portugueses e 2 artigos de brasileiros com espanhóis. As 3 áreas em preto mostram 1 artigo com autoria exclusiva de costarricense, outro de uruguayo e outro espanhol.

- Validei os número do Tableau fazendo a "prova dos nove" com contagem manual nos dados do Excel. Se puder fazer o mesmo para uma dupla checagem, seria perfeito para termos segurança.

- Sobre a sua dúvida: Penso que é possível gerar um arquivo PDF com o printscreen das telas, junto com o link do Tableau, caso o comitê desejar explocar dinamicamente os dados.

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula conseguiu verificar os meus comentarios?

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki desculpe a demora.  Agradecemos as mudanças realizadas, que melhoraram bastante a visualização! 

Conversei com a @suelisuga e gostaríamos de verificar a possibilidade de mais alguns ajustes:

• Predominância de Estado: diminuir fonte
![image](https://user-images.githubusercontent.com/47643830/91482529-96b11d80-e87c-11ea-8dd2-db60281c7e1c.png)


• Separar os grupos (autores, comitê e revisores), para evitar muitas linhas e facilitar visualização
![image](https://user-images.githubusercontent.com/47643830/91482449-77b28b80-e87c-11ea-8dd4-0872eb0b054a.png)

Obrigada!

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula A fonte da lista de predominância de estado foi reduzida de 15 para 12. 

Já em relação à separação dos grupos, para fazê-lo teríamos que separar em mais de um painel, pois não caberia no painel atual. Nesse caso teríamos, ao invés de 2 painéis (Planilha Autores e Planilha Artigos), 4 painéis (Planilha Autores, Planilha Artigos/Autores, Planilha Artigos/Comitê Editorial e Planilha Artigos/Revisores). Nessas novas planilhas, tanto o grupo por instituições, como de estado e país seriam afetados para mostrar somente Autores, ou Comitê Editorial ou Revisores. Antes de fazer essa mudança, sugiro provar, se ainda não o fez, o uso do ordenamento decrescente das colunas de Autores, Comitê Editorial e Revisores. Colocar em ordem decrescente a coluna que estiver analisando fará com que as linhas com 0 ocorrências fiquem por último, não atrapalhando a sua leitura.

Aguardo seu parecer sobre minha sugestão.

**Comment by AngelicaSAPaula** [comment]
@renatomurasaki muito obrigada!

Passando a comemoração dos 35 anos da LILACS, me reunirei com a equipe do FIR e colocarei isto em pauta para discussão!

**Comment by renatomurasaki** [comment]
@AngelicaSAPaula podemos encerrar esse issue, considerando meu comentario anterior?

**Comment by AngelicaSAPaula** [comment]
Acredito que podemos encerrar, sim! Obrigada!
